AWSTemplateFormatVersion: 2010-09-09
Description: Template to set up the cross account role
Parameters:
  TrustedRoleARNs:
    Description: Comma delimited role ARNs allowed to access the S3 bucket on customer side
    Type: CommaDelimitedList
  ExternalId:
    Description: External ID used to create the cross account role
    Type: String
    AllowedPattern: '[a-zA-Z]*-[a-zA-Z]*'
  SharedS3Bucket:
    Description: S3 bucket name to be shared
    Type: String
Resources:
  CrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref TrustedRoleARNs
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      Path: /
      Policies:
        - PolicyName: AllowS3ListRead
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource:
                  - !Join 
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref SharedS3Bucket
                  - !Join 
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref SharedS3Bucket
                      - /*
Outputs:
  S3Region:
    Value: !Ref 'AWS::Region'
    Description: Region of the shared S3 bucket
  CrossAccountRoleARN:
    Value: !GetAtt 
      - CrossAccountRole
      - Arn
    Description: ARN of the cross account role
